### PR TITLE
Builder static factory method

### PR DESCRIPTION
**Pull request by yccheok**
Re-submit to merge into develop branch.

### CODE REVIEW

**Comment by yccheok** [comment]
Hem... No idea why there are so many conflict.

**Comment by luizgrp** [comment]
did you pull the latest develop?

**Comment by yccheok** [comment]
I'm not kinna familiar with github flow. Perhaps I will just delete my forked repo, and redo again.

Should I request to merge to `develop` branch? As, `develop` branch contains "thread safety" change, which I believe you're going to abandon - https://github.com/luizgrp/SectionedRecyclerViewAdapter/issues/75 ?

**Comment by luizgrp** [comment]
Yes, merge into develop, I will revert the changes from 75 once this and 98 gets merged.

**Comment by luizgrp** [comment]
Done in commit d24039649d84c76c955b426805b7463d5427d933

**Pull request closed without merging**
