### PR TITLE
Bug fixed.

### PR DESCRIPTION
**Pull request by yccheok**
Sorry for the missing thingy

### CODE REVIEW

**Comment by luizgrp** [comment]
no worries, next week I will update the demo app to include the empty state and will see if we can write an unit test to cover the constructor with SectionParameters

**Comment by yccheok** [comment]
2017-07-01 03_06_25-store

@luizgrp 

Not sure why. After updating the gradle.build to 1.1.1, I'm still getting the old code although I had tried to restart the IDE and rebuild multiple times.

Any idea?

**Comment by yccheok** [comment]
@luizgrp 

I think something went wrong during the merge process?

Because if I look at the master branch 

https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/library/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/Section.java#L95

The fix isn't there. Seem weird ?!

**Comment by luizgrp** [comment]
@yccheok 
very weird, I must have messed up with the develop branch
thanks for spotting that, hope everything is fine in v1.1.2 :crossed_fingers:

**Comment by yccheok** [comment]
@luizgrp 

Thank you. Works good now. +1

**Pull request merged**
